import React from 'react';
import type { Metadata } from 'next';
import './styles/globals.scss';
import { RobotoCondensed } from './fonts';
import SVG from 'react-inlinesvg';
import styles from './page.module.scss';
import { Container } from './components/general/Container/Container';
import logoImage from '@public/peleng_logo.svg';
import { Menu } from './components/general/Menu/Menu';

const navigateData = [
  { id: '0', title: 'ГЛАВНАЯ', address: '/' },
  { id: '1', title: 'О КОМПАНИИ', address: '/about' },
  { id: '2', title: 'КАТАЛОГИ', address: '/catalogs' },
  { id: '3', title: 'СПРАВОЧНИКИ', address: '/guide' },
  { id: '4', title: 'СОТРУДНИКУ', address: '/employee' },
];

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={RobotoCondensed.className}>
        <Container>
          <SVG src={logoImage.src} title="peleng-logo" className={styles.logoImage} />
        </Container>
        <Menu navigateData={navigateData} />
        {children}
      </body>
    </html>
  );
}
